# location to mount remote filesystem
# - folder should exist
# - on Windows you can mount volumes (e.g. "X:\")
mpoint = "/mnt/mimic"

# server hosting webdav
url = "https://webdav.exaple.com"

# server credentials
username = "user"
password = "pass"

# cache
ttl = "1s" # important to be in quotes!
max-entries = 100

# logger
verbose = true

# possile values for streams are:
# - "stdout" (only for 'std')
# - "stderr" (only for 'err')
# - "discard" - ignores the stream
# - file path (program will create the path if it doesn't exist)
err = "stderr"
std = "stdout"